app:
  password: "1234567890"

connection:
  ip: "127.0.0.1" # 192.168.0.11
  port: 7860
  share: false

windows:  # It works only from windows
  poppler_bin_path: "C:/poppler/poppler-24.08.0/Library/bin"  # leave empty ("") if no need to use
